export const DISORDER_OPTIONS = [
  {
    key: "Amputaciones o malformaciones congénitas",
    text: "Amputaciones o malformaciones congénitas",
  },
  { key: "Artritis juvenil", text: "Artritis juvenil" },
  {
    key: "Ceguera o discapacidad visual",
    text: "Ceguera o discapacidad visual",
  },
  { key: "Depresión mayor", text: "Depresión mayor" },
  { key: "Diabetes tipo 1", text: "Diabetes tipo 1" },
  { key: "Discalculia", text: "Discalculia" },
  { key: "Dislexia", text: "Dislexia" },
  { key: "Distrofia muscular", text: "Distrofia muscular" },
  { key: "Epilepsia", text: "Epilepsia" },
  { key: "Esclerosis múltiple", text: "Esclerosis múltiple" },
  { key: "Espina bífida", text: "Espina bífida" },
  { key: "Fibrosis quística", text: "Fibrosis quística" },
  {
    key: "Lesiones cerebrales traumáticas",
    text: "Lesiones cerebrales traumáticas",
  },
  { key: "Parálisis cerebral", text: "Parálisis cerebral" },
  { key: "Síndrome alcohólico fetal", text: "Síndrome alcohólico fetal" },
  { key: "Síndrome de Asperger", text: "Síndrome de Asperger" },
  { key: "Síndrome de Down", text: "Síndrome de Down" },
  { key: "Síndrome de Turner", text: "Síndrome de Turner" },
  { key: "Síndrome de X frágil", text: "Síndrome de X frágil" },
  { key: "Sordera o pérdida auditiva", text: "Sordera o pérdida auditiva" },
  { key: "Sordoceguera", text: "Sordoceguera" },
  { key: "TEA", text: "TEA" },
  { key: "TDAH", text: "TDAH" },
  { key: "Trastorno bipolar", text: "Trastorno bipolar" },
  {
    key: "Trastorno de ansiedad generalizada",
    text: "Trastorno de ansiedad generalizada",
  },
  {
    key: "Trastornos del desarrollo intelectual",
    text: "Trastornos del desarrollo intelectual",
  },
  { key: "Esquizofrenia", text: "Esquizofrenia" },
];
