import { IDynamicFormField } from "@/lib/types/type";
import { defaultDisorderOptions, defaultEducationalStageOptions, defaultLevelOptions, defaultModalityOptions } from "@/lib/utils/options";

export const anualPlanFormFields: IDynamicFormField[] = [
  {
    type: "dropdown",
    label: "Etapa educativa",
    name: "etapa educativa",
    placeholder: "Seleccione una opción...",
    col: 1,
    options: defaultEducationalStageOptions,
    required: true,
  },
  {
    type: "dropdown",
    label: "Modalidad",
    name: "modalidad",
    placeholder: "Seleccione una opción...",
    col: 1,
    options: defaultModalityOptions,
    required: true,
  },
  {
    type: "text",
    label: "Nombre del alumno",
    name: "nombre",
    placeholder: "Introduzca un nombre de alumno...",
    col: 2,
    required: true,
  },
  {
    type: "slider",
    label: "Edad",
    name: "edad",
    col: 2,
    min: 0,
    max: 50,
    step: 1,
    required: true,
  },
  {
    type: "dropdown",
    label: "Tipo de discapacidad",
    name: "discapacidad",
    placeholder: "Seleccione una o varias opciones...",
    col: 4,
    options: defaultDisorderOptions,
    isMultiSelect: true,
  },
  {
    type: "dropdown",
    label: "Coeficiente intelectual",
    name: "coeficiente intelectual",
    placeholder: "Seleccione una opción...",
    col: 4,
    options: defaultLevelOptions,
    required: true,
  },
  {
    type: "dropdown",
    label: "Psicomotricidad fina",
    name: "psicomotricidad fina",
    placeholder: "Seleccione una opción...",
    col: 5,
    options: defaultLevelOptions,
    required: true,
  },
  {
    type: "dropdown",
    label: "Psicomotricidad gruesa",
    name: "psicomotricidad gruesa",
    placeholder: "Seleccione una opción...",
    col: 5,
    options: defaultLevelOptions,
    required: true,
  },

  {
    type: "dropdown",
    label: "Comunicacion escrita",
    name: "comunicacion escrita",
    placeholder: "Seleccione una opción...",
    col: 6,
    options: defaultLevelOptions,
    required: true,
  },
  {
    type: "dropdown",
    label: "Comunicacion verbal",
    name: "comunicacion verbal",
    placeholder: "Seleccione una opción...",
    col: 6,
    options: defaultLevelOptions,
    required: true,
  },
  {
    type: "dropdown",
    label: "Intencionalidad comunicativa",
    name: "intencionalidad comunicativa",
    placeholder: "Seleccione una opción...",
    col: 7,
    options: defaultLevelOptions,
    required: true,
  },
  {
    type: "text",
    label: "Observaciones",
    name: "observaciones",
    placeholder: "Si lo desea, deje sus observaciones...",
    col: 8,
    rows: 5,
    isMultiline: true,
  },
];
