import { IDynamicFormField } from "@/lib/types/type";
import { defaultDisorderOptions, defaultLevelOptions } from "@/lib/utils/options";

export const addSingleStudentField: IDynamicFormField[] = [
  {
    type: "text",
    label: "Nombre del alumno",
    name: "nombre",
    placeholder: "Introduzca un nombre de alumno...",
    col: 1,
    required: true,
  },
  {
    type: "number",
    label: "Edad",
    name: "edad",
    col: 2,
    min: 0,
    max: 50,
    step: 1,
    required: true,
  },
  {
    type: "dropdown",
    label: "Coeficiente intelectual",
    name: "coeficienteIntelectual",
    placeholder: "Seleccione una opción...",
    col: 2,
    options: defaultLevelOptions,
  },
  {
    type: "dropdown",
    label: "Intencionalidad Comunicativa",
    name: "intencionalidadComunicativa",
    placeholder: "Seleccione una opción...",
    col: 3,
    options: defaultLevelOptions,
  },
  {
    type: "dropdown",
    label: "Tipo de discapacidad",
    name: "discapacidad",
    placeholder: "Seleccione una o varias opciones...",
    col: 3,
    options: defaultDisorderOptions,
    isMultiSelect: true,
  },
  {
    type: "dropdown",
    label: "Psicomotricidad Fina",
    name: "psicomotricidadFina",
    placeholder: "Seleccione una opción...",
    col: 4,
    options: defaultLevelOptions,
  },
  {
    type: "dropdown",
    label: "Psicomotricidad Gruesa",
    name: "psicomotricidadGruesa",
    placeholder: "Seleccione una opción...",
    col: 4,
    options: defaultLevelOptions,
  },

  {
    type: "dropdown",
    label: "Comunicacion Escrita",
    name: "comunicacionEscrita",
    placeholder: "Seleccione una opción...",
    col: 5,
    options: defaultLevelOptions,
  },
  {
    type: "dropdown",
    label: "Comunicacion Verbal",
    name: "comunicacionVerbal",
    placeholder: "Seleccione una opción...",
    col: 5,
    options: defaultLevelOptions,
  },
  {
    type: "text",
    label: "Observaciones",
    name: "observaciones",
    placeholder: "Si lo desea, deje sus observaciones...",
    col: 7,
    isMultiline: true,
  },
];
